const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const html=fs.readFileSync('app.html','utf8');
function fn(n){let i=html.indexOf('async function '+n+'(');if(i<0)i=html.indexOf('function '+n+'(');return html.slice(i,html.indexOf('\n}',i)+2);}
function fixture(old,fail){const calls=[];const client={from:()=>({select:()=>({eq:async()=>({data:old,error:fail==='read'?Error('offline'):null})}),upsert:async rows=>{calls.push(['upsert',rows]);return {error:fail==='write'?Error('offline'):null}},delete:()=>({eq:()=>({in:async(k,ids)=>{calls.push(['delete',ids]);return {error:fail==='delete'?Error('offline'):null}}})})})};const c={crypto:{randomUUID:()=> 'new-id'}};vm.createContext(c);vm.runInContext(fn('syncRosterSafely'),c);return {c,client,calls};}
test('Rosa invariata: nessuna scrittura; ID stabili per modifiche',async()=>{const row={player_name:'Rossi',role:'D',team:'Roma',position:0};const f=fixture([{...row,id:'existing'}]);await f.c.syncRosterSafely(f.client,'league',[row]);assert.equal(f.calls.length,0);await f.c.syncRosterSafely(f.client,'league',[{...row,position:1}]);assert.equal(f.calls[0][1][0].id,'existing');assert.equal(f.calls.length,1);});
test('Errore upsert: nessun vecchio giocatore viene cancellato',async()=>{const f=fixture([{id:'old',player_name:'Old'}],'write');await assert.rejects(()=>f.c.syncRosterSafely(f.client,'league',[{player_name:'New'}]));assert.deepEqual(f.calls.map(c=>c[0]),['upsert']);});
test('Solo dopo conferma scrittura si eliminano gli ID obsoleti',async()=>{const f=fixture([{id:'old',player_name:'Old'}]);await f.c.syncRosterSafely(f.client,'league',[{player_name:'New'}]);assert.deepEqual(f.calls.map(c=>c[0]),['upsert','delete']);assert.equal(f.calls[1][1][0],'old');});
test('Errore lettura: nessuna modifica; errore rimozione non viene nascosto',async()=>{for(const error of ['read','delete']){const f=fixture([{id:'old',player_name:'Old'}],error);await assert.rejects(()=>f.c.syncRosterSafely(f.client,'league',[{player_name:'New'}]));if(error==='read')assert.equal(f.calls.length,0);}});
test('Consultazione Oracle non riscrive snapshot e non dichiara titolarità dalle sole presenze',()=>{const run=fn('runOracleEngine');assert(run.includes('if (!silent && calendario.giornate.length'));assert(run.includes('if (!silent) { oracleSaveState(); saveRosterToStorage(); }'));const predict=fn('oraclePredictPlayer');assert(!predict.includes("risk = 'titolarità incerta'"));assert(predict.includes("risk = 'campione ridotto'"));});
test('Diagnostica pubblica: solo codici consentiti, nessun dato utente nei log',()=>{const logs=[];const c={console:{warn:(...x)=>logs.push(x)}};vm.createContext(c);vm.runInContext(fs.readFileSync('api/client-error.js','utf8').replace('export default function handler','function handler'),c);let status;const res={setHeader(){},status(n){status=n;return this},end(){}};c.handler({method:'POST',headers:{origin:'https://fantaoracle.ch'},body:{code:'cloud_sync',email:'private@example.com'}},res);assert.equal(status,204);assert(!JSON.stringify(logs).includes('private'));c.handler({method:'POST',headers:{origin:'https://fantaoracle.ch'},body:{code:'unknown'}},res);assert.equal(status,400);c.handler({method:'POST',headers:{origin:'https://other.example'},body:{code:'runtime'}},res);assert.equal(status,403);});
