const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const Core=require('../assets/support-core');
test('Assistente: importazione senza lega, calendari associati e regolamento sconosciuto',()=>{assert.match(Core.answer('Importa rosa',{}),/esporta il file delle rose/);assert.match(Core.answer('Calendari',{league:'Premier',calendars:3}),/Calendari presenti: 3/);assert.match(Core.answer('modificatore',{}),/non è ancora verificato/);});
test('Assistente: spiegazioni dal calcolo presente, mai motivi inventati senza analisi',()=>{assert.match(Core.answer('spiega',{selected:{name:'Rossi'}}),/non ho ancora un’analisi/);const a=Core.answer('spiega',{selected:{name:'Rossi',starter:false,info:{expected:6.4,factors:['avversario difficile'],risk:'campione ridotto'}}});assert.match(a,/avversario difficile/);assert.match(a,/non una notizia di mancata titolarità/);assert.match(a,/non costituiscono una spiegazione causale completa/);});
test('Assistente: la scelta manuale è distinta dal consiglio e nessuna domanda modifica dati',()=>{const context={manual:'3-4-3',best:{modulo:'4-3-3'}};const before=JSON.stringify(context);assert.match(Core.answer('modulo',context),/scelto manualmente 3-4-3/);assert.equal(JSON.stringify(context),before);assert.match(Core.answer('chi vincerà domani?',{}),/assistente guidato/);});
function setup(responses){const calls=[];let code,body,headers={};const c={process:{env:{SUPABASE_URL:'https://db.example',SUPABASE_ANON_KEY:'public',SUPABASE_SERVICE_ROLE_KEY:'private'}},console:{warn(){}},AbortSignal:{timeout:()=>undefined},crypto:{randomUUID:()=> 'id'},fetch:async(url,options)=>{calls.push({url,options});const result=responses.shift();assert(result,'unexpected fetch '+url);return {ok:result.status>=200&&result.status<300,status:result.status,json:async()=>result.body}}};vm.createContext(c);vm.runInContext(fs.readFileSync('api/notices.js','utf8').replace('export default function handler','async function handler').replace('export default async function handler','async function handler'),c);const res={setHeader(k,v){headers[k]=v},status(n){code=n;return this},json(x){body=x;return this}};return {run:async req=>{await c.handler(req,res);return {code,body,headers,calls}}};}
const auth={status:200,body:{id:'user'}};const admin={status:200,body:[{is_admin:true}]};const notice={title:'Servizio',message:'Messaggio di prova',type:'info',expiresAt:new Date(Date.now()+3600000).toISOString()};
test('Avvisi: lettura iniziale senza bucket, errori di rete non diventano assenza di avvisi',async()=>{let result=await setup([{status:400,body:{message:'Object not found'}}]).run({method:'GET'});assert.equal(result.code,200);assert.equal(result.body.notice,null);result=await setup([{status:503}]).run({method:'GET'});assert.equal(result.code,503);});
test('Avvisi: utenti normali e richieste anonime non possono pubblicare',async()=>{let result=await setup([]).run({method:'POST',headers:{},body:notice});assert.equal(result.code,401);result=await setup([auth,{status:200,body:[{is_admin:false}]}]).run({method:'POST',headers:{authorization:'Bearer user'},body:notice});assert.equal(result.code,403);assert.equal(result.calls.length,2);});
test('Avvisi: admin pubblica con storage privato e scadenza, senza esporre chiavi',async()=>{const result=await setup([auth,admin,{status:404},{status:200},{status:200}]).run({method:'POST',headers:{authorization:'Bearer admin',origin:'https://fantaoracle.ch'},body:notice});assert.equal(result.code,200);assert.equal(JSON.parse(result.calls[3].options.body).public,false);assert(!JSON.stringify(result.body).includes('private'));assert.equal(result.body.notice.title,'Servizio');});
test('Avvisi: scaduti invisibili, input invalido rifiutato prima di scrivere, ritiro confermato solo su successo',async()=>{let result=await setup([{status:200,body:{...notice,expiresAt:'2000-01-01'}}]).run({method:'GET'});assert.equal(result.body.notice,null);result=await setup([auth,admin]).run({method:'POST',headers:{authorization:'Bearer admin'},body:{...notice,title:'x'.repeat(121)}});assert.equal(result.code,400);result=await setup([auth,admin,{status:200},{status:500}]).run({method:'POST',headers:{authorization:'Bearer admin'},body:{action:'withdraw'}});assert.equal(result.code,503);});
